SELECT P.CODPROD, P.CODAUXILIAR AS GTIN, P.NBM, P.DESCRICAO AS DESCRICAO_ERP
FROM PCPRODUT P
WHERE P.CODAUXILIAR IS NOT NULL 
  AND LENGTH(P.CODAUXILIAR) IN (8, 12, 13, 14)
  AND P.DTEXCLUSAO IS NULL
  AND P.REVENDA = 'S'
  AND P.CODEPTO NOT IN (0, 14, 16, 17, 18, 19, 20)

UNION

SELECT E.CODPROD, E.CODAUXILIAR AS GTIN, P.NBM, P.DESCRICAO AS DESCRICAO_ERP
FROM PCEMBALAGEM E
JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
WHERE E.CODAUXILIAR IS NOT NULL 
  AND LENGTH(E.CODAUXILIAR) IN (8, 12, 13, 14)
  AND E.DTINATIVO IS NULL
  AND P.REVENDA = 'S'
  AND P.CODEPTO NOT IN (0, 14, 16, 17, 18, 19, 20)

ORDER BY CODPROD, GTIN
